---
apiVersion: v1
data:
  nginx.conf: |+

    user  nginx;
    worker_processes  1;

    error_log  /dev/stderr warn;

    events {
      worker_connections 1024;
    }
    stream {
        upstream tservers {
          # Change the address here to the correct database tserver service address
          server yb-tservers.yb-demo-demodb.svc.cluster.local:5433 max_fails=2 fail_timeout=30s;
        }

        server {
            listen 5433 so_keepalive=on;
            proxy_pass tservers;

            # Maximum time to wait for connecting to the YB server. 1 second is okay since its all local connections
            proxy_connect_timeout 1s;

            # Maximum query execution time. LB will terminate any connection query taking longer then this time
            # 30sec in dev is reasonable. But you can change it as per your application query times
            proxy_timeout 30s;
        }

    }
kind: ConfigMap
metadata:
  name: yb-tserver-proxy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yb-tserver-proxy
  name: yb-tserver-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yb-tserver-proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: yb-tserver-proxy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5433
          name:  ysql
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx
      volumes:
      - name: nginx-conf
        configMap:
          name: yb-tserver-proxy
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yb-tserver-proxy
  name: yb-tserver-proxy
spec:
  ports:
  - name: tserver
    port: 5433
    protocol: TCP
    targetPort: 5433
  selector:
    app: yb-tserver-proxy
  type: ClusterIP
